# Generated by Django 2.0.4 on 2019-03-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0002_auto_20190311_1949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invites',
            new_name='Invite',
        ),
        migrations.AddField(
            model_name='league',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
