# Generated by Django 2.0.4 on 2019-03-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0003_auto_20190311_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
