# Generated by Django 2.0.4 on 2019-03-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0005_auto_20190311_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='league',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
