# Generated by Django 2.0.4 on 2019-03-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0006_auto_20190312_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
