# Generated by Django 2.0.4 on 2019-03-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0007_auto_20190312_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
