# Generated by Django 2.0.4 on 2019-03-12 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0008_auto_20190312_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='golf_app.League'),
        ),
    ]
