# Generated by Django 2.0.4 on 2019-03-12 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0009_auto_20190312_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='golf_app.League'),
        ),
    ]
