# Generated by Django 2.0.4 on 2019-03-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0010_auto_20190312_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='no_cut_bonus',
            field=models.IntegerField(default=-50),
        ),
        migrations.AddField(
            model_name='league',
            name='stakes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='league',
            name='stakes_types',
            field=models.CharField(choices=[('1', 'Weekly'), ('2', 'Season 50/50'), ('3', 'Season 75/25')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='winner_bonus',
            field=models.IntegerField(default=-50),
        ),
    ]
