# Generated by Django 2.0.4 on 2019-04-12 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('golf_app', '0012_auto_20190401_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/golf_app/avatar/'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('league', 'name')},
        ),
    ]
