# Generated by Django 2.0.4 on 2019-04-14 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0013_auto_20190412_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='invite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='golf_app.Invite'),
        ),
        migrations.AlterField(
            model_name='league',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
