# Generated by Django 2.0.4 on 2019-04-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_app', '0014_auto_20190414_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
